/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Company;
import io.swagger.model.Contact;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-03T17:12:18.187Z")

@Api(value = "companies", description = "the companies API")
public interface CompaniesApi {

    @ApiOperation(value = "List all the companies", nickname = "companiesGet", notes = "", response = Company.class, responseContainer = "List", tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Company.class, responseContainer = "List") })
    @RequestMapping(value = "/companies",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Company>> companiesGet(@ApiParam(value = "Substring to search for", defaultValue = "") @Valid @RequestParam(value = "search", required = false, defaultValue="") String search);


    @ApiOperation(value = "List all the contacts of a company", nickname = "companiesIdContactsGet", notes = "", response = Contact.class, responseContainer = "List", tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Contact.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Company not found") })
    @RequestMapping(value = "/companies/{id}/contacts",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Contact>> companiesIdContactsGet(@ApiParam(value = "Company id to list contacts",required=true) @PathVariable("id") Long id,@ApiParam(value = "Substring to search for", defaultValue = "") @Valid @RequestParam(value = "search", required = false, defaultValue="") String search);


    @ApiOperation(value = "Create a contact of company", nickname = "companiesIdContactsPost", notes = "", tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Company not found"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/companies/{id}/contacts",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> companiesIdContactsPost(@ApiParam(value = "Company id to create contact",required=true) @PathVariable("id") Long id,@ApiParam(value = "Contact object that needs to be added" ,required=true )  @Valid @RequestBody Contact body);


    @ApiOperation(value = "Deletes a company", nickname = "companiesIdDelete", notes = "", tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Company not found") })
    @RequestMapping(value = "/companies/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> companiesIdDelete(@ApiParam(value = "Company id to delete",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "Find company by ID", nickname = "companiesIdGet", notes = "Returns a single company", response = Company.class, tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Company.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Company not found") })
    @RequestMapping(value = "/companies/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Company> companiesIdGet(@ApiParam(value = "ID of company to return",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "Updates a company with form data", nickname = "companiesIdPut", notes = "", tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/companies/{id}",
        produces = { "application/json" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> companiesIdPut(@ApiParam(value = "ID of company that needs to be updated",required=true) @PathVariable("id") Long id,@ApiParam(value = "Updated name of the company") @RequestParam(value="name", required=false)  String name);


    @ApiOperation(value = "Create a company", nickname = "companiesPost", notes = "", tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/companies",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> companiesPost(@ApiParam(value = "Company object that needs to be added" ,required=true )  @Valid @RequestBody Company body);

}
